#!/usr/bin/env bash
sudo cp /etc/hosts ~/hosts.new
sudo sed -i 's/^.*localhost/127.0.0.2 localhost/g' ~/hosts.new
sudo sed -i '/facebook.com/d' ~/hosts.new
echo "8.8.8.8 facebook.com" | sudo tee -a ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
